[package]
name = "flac-reencoder"
version = "0.1.2"
edition = "2024"
repository = "https://github.com/justjakka/reencoder/"
license = "BSD-3-Clause"
authors = ["jakka"]
description = "A tool for keeping your flacs up-to-date"
categories = ["command-line-utilities"]
keywords = ["flac", "audio"]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["cargo", "help", "std"] }
clap_complete = "4.5.54"
directories = "6.0.0"
flac-bound = { version = "0.5.0", features = [
    "libflac-noogg",
], default-features = false }
futures-util = "0.3.31"
i24 = { version = "2.1.0", features = ["std"] }
indicatif = { version = "0.17.11", features = [
    "tokio",
    "improved_unicode",
    "futures",
] }
libsql = { version = "0.9.11" }
md-5 = "0.10.6"
pin-utils = "0.1.0"
tokio = { version = "1.45.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "signal",
] }
tokio-util = "0.7.15"
walkdir = "2.5.0"
console = { version = "0.15.11", features = ["windows-console-colors"] }
claxon = { git = "https://github.com/justjakka/claxon.git" }
metaflac = "0.2.8"
