[package]
name = "reencoder"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/justjakka/reencoder/"

[dependencies]
anyhow = "1.0.98"
directories = "6.0.0"
flac-bound = { version = "0.5.0", features = ["libflac-noogg"], default-features = false }
futures-util = "0.3.31"
i24 = "2.1.0"
libsql = { version = "0.9.10", default-features = false, features = ["core", "sync"] }
md-5 = "0.10.6"
metaflac = "0.2.8"
symphonia = { version = "0.5.4", path = "../Symphonia/symphonia", default-features = false, features = ["flac"] }
tokio = { version = "1.45.1", features = ["macros", "rt", "rt-multi-thread"] }
#symphonia = { git = "https://github.com/pdeljanov/Symphonia.git", branch = "dev-0.6", default-features = false, features = ["flac"] }
