[package]
name = "reencoder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
flac-bound = { version = "0.5.0", features = ["libflac-noogg"], default-features = false }
symphonia = { version = "0.5.4", default-features = false, features = ["flac"] }
symphonia-metadata = "0.5.4"
tokio = "1.45.1"
